Popcorn/Popcorn/Controllers/DadfolioController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Popcorn.Data;
using Popcorn.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace Popcorn.Controllers
{
    public class DadfolioController : Controller
    {
        private readonly PopcornDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DadfolioController(PopcornDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        //GET
        [HttpGet]
        public IActionResult Index()
        {
            return View(_context.Profiles);
        }

        //POST
        //[HttpPost]
        //would change parameter to string answerChoicec instead in order to add response data to response database
        public async Task<IActionResult> TakeQuiz(Profiles profiles)
        {
            var DbProfiles = _context.Profiles;
            var currentUser = await _userManager.GetUserAsync(User);
            var currentUserId = _context.Profiles.Where(w => w.ApplicationUserId == currentUser.Id);

            List<Answers> answerList = _context.Answers.ToList();
            ViewBag.Responses = _context.Responses;
            ViewBag.Answers = answerList;
            ViewBag.UserQuestions = _context.Questions;
            ViewBag.UserAnswers = _context.Answers;

            await _context.AddAsync(profiles);
            //await _context.SaveChangesAsync();

            return View();           

        }

        //PUT
        [HttpPut]
        public async Task<IActionResult> Put(int id, Profiles profiles)
        {
            if(!ModelState.IsValid)
            {
                BadRequest(ModelState);
            }

            var check = _context.Profiles.FirstOrDefault(w => w.Id == id);

            if (check != null)
            {
                check.ApplicationUserId = profiles.ApplicationUserId;
                check.AnswersId = profiles.AnswersId;
                check.QuestionsId = profiles.QuestionsId;
                check.ResponsesId = profiles.ResponsesId;
                _context.Update(check);
                await _context.SaveChangesAsync();
                return CreatedAtAction("Index", new { id = profiles.Id }, profiles);
            }
            else if(check == null)
            {
                await TakeQuiz(profiles);
            }
            return BadRequest();
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var result = _context.Profiles.FirstOrDefault(w => w.Id == id);

            if(result != null)
            {
                _context.Profiles.Remove(result);
                await _context.SaveChangesAsync();
                return Ok();
            }
            return BadRequest();
        }
    }
}

Popcorn/Popcorn/Controllers/MatchesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Popcorn.Data;
using Popcorn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Popcorn.Controllers
{
    public class MatchesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly PopcornDbContext _popcornContext;

        public MatchesController(UserManager<ApplicationUser> userManager, ApplicationDbContext context, PopcornDbContext popcornContext)
        {
            _userManager = userManager;
            _context = context;
            _popcornContext = popcornContext;
        }

        public async Task<IActionResult> Index()
        {
            // Get currently logged in User
            var currentUser = await _userManager.GetUserAsync(User);
            // Get any Matches where the currentUser was "liked"
            var currentUserMatches = _popcornContext.Matches.Where(p => p.UserMatchedId == currentUser.Id);
            // Initialize a list of User objects to hold any matched Users
            List<ApplicationUser> matchedUsers = new List<ApplicationUser>();
            // Get any User that the current User has "liked" and has been "liked" by
            foreach (var match in currentUserMatches)
            {
                // Get any Matches where the Current User "liked" Users who have "liked" them already
                var isMatch = _popcornContext.Matches.Where(j => j.UserMatchedId == match.UserMatchingId && j.UserMatchingId == currentUser.Id);
                if (isMatch.ToList().Count() > 0)
                {
                    var item = isMatch.First().UserMatchedId;
                    // Get any User from the context where the User's Id 
                    var matchedUser = _context.ApplicationUser.Where(m => m.Id == item);
                    
                    matchedUsers.Add(matchedUser.First()); 
                    
                }
            }
            return View(matchedUsers);
        }
    }
}

Popcorn/Popcorn/Views/Shared/_Layout.cshtml
@using System.Security.Claims;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/StyleSheet.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
</head>
<body>

    @*bootstrap navbar*@
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Popcorn</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Browse" asp-action="Index">Browse</a></li>
                <li><a asp-controller="Matches" asp-action="Index">Matches</a></li>
                <li><a asp-controller="Dadfolio" asp-action="TakeQuiz">Dadfolio</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a asp-controller="Account" asp-action="Login">Login</a></li>
                <li><a asp-controller="Account" asp-action="Register">Register</a></li>
                <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
            </ul>
        </div>
    </nav>



    <div>
        @if (!User.Identities.Any(u => u.IsAuthenticated))
        {
            <span class="greeting">Welcome, guest!</span>

        }
        else
        {

            <span class="greeting">
                Welcome back, Pop!
            </span>

        }
    </div>

    <div>
        @RenderBody()
    </div>
</body>
</html>